services:
  filecloud:
    container_name: FileCloud
    build:
      context: ./FileCloud
      dockerfile: Dockerfile
    ports:
      - "32772:8080"
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "FileCloudDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
 
networks:
  app-network:
    name: FileCloud-network
    driver: bridge

volumes:
  postgres-data: